[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "phylotypy"
version = "0.2.0"
description = "Naive Bayes Classifier"
authors = [
    {name = "Chad Saltikov",email = "saltikov@ucsc.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "biopython",
    "numpy",
    "pandas",
    "scikit-learn",
    "requests",
]
[project.optional-dependencies]
test = [
    "pytest",
]
