[build-system]
requires = ["setuptools>=45", "wheel", "Cython>=0.29.21", "numpy"]
build-backend = "setuptools.build_meta"

[tool.cython]
language_level = "3"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["*.pyx", "*.pxd"]

[project]
name = "phylotypy"
version = "0.2.0"
description = "Naive Bayes Classifier with Rust-accelerated taxonomy functions"
authors = [
    {name = "Chad Saltikov", email = "saltikov@ucsc.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "setuptools",
    "biopython",
    "numpy",
    "numba",
    "pandas",
    "scikit-learn",
    "requests",
    "pandarallel",
    "jax",
    "cython"
]

[project.optional-dependencies]
test = [
    "pytest",
]

