[project]
name = "phylotypy"
version = "0.1.0"
description = "Naive Bayes Classifier"
authors = [
    {name = "Chad Saltikov",email = "saltikov@ucsc.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "biopython>=1.84",
    "ipython>=8.31.0",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
[project.optional-dependencies]
test = [
    "pytest>=7.0",
]
[tool.setuptools.packages.find]
include = ["data*", "training_data*"]
